---
name: Bug Report
about: Report a problem with the tool
title: "[Bug] "
labels: bug
assignees: ''

body:
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      placeholder: What did you do to trigger this?
    validations:
      required: true

  - type: input
    attributes:
      label: Browser or OS
      placeholder: Chrome, Firefox, Windows 11, etc.
